POST http://localhost:8080/users
Content-Type: application/json

{
    "fullName": "Test Doctor 6",
    "email": "testdoctor6@gmail.com",
    "password": "test123",
    "phone": "9876543215",
    "role": "DOCTOR"
}
### Get all users
GET http://localhost:8080/users
Content-Type: application/json

{
  "fullName": "Test Doctor 2",
  "email": "testdoctor2@gmail.com",
  "password": "test123",
  "phone": "9876543213",
  "role": "Doctor"
}
### Update User
PUT http://localhost:8080/users/5
Content-Type: application/json

{
  "fullName": "Updated Doctor",
  "email": "updateddoctor@gmail.com",
  "phone": "9876543000",
  "role": "Doctor"
}
### Delete User
DELETE http://localhost:8080/users/5

### ADD DOCTOR AVAILABILITY

POST http://localhost:8080/availability
Content-Type: application/json

{
  "doctorId": 1,
  "availableDate": "2026-08-20",
  "availableTime": "10:00:00"
}





###Login
POST http://localhost:8080/users/login
Content-Type: application/json

{
    "email": "marimuthu987@gmail.com",
    "password": "ananthi@123"
}

### Create Appointment

POST http://localhost:8080/appointments
Content-Type: application/json

{
  "doctorId": 1,
  "patientId": 2,
  "appointmentDate": "2026-08-15",
  "appointmentTime": "10:00:00",
  "status": "Booked"
}

### Get All Appointments

GET http://localhost:8080/appointments
Content-Type: application/json

### Get Appointment By ID

GET http://localhost:8080/appointments/1
Content-Type: application/json

### Update Appointment

PUT http://localhost:8080/appointments/1
Content-Type: application/json

{
  "doctorId": 1,
  "patientId": 2,
  "appointmentDate": "2026-08-16",
  "appointmentTime": "11:30:00",
  "status": "Confirmed"
}
###
DELETE http://localhost:8080/appointments/3



### ADD DOCTOR AVAILABILITY

POST http://localhost:8080/availability
Content-Type: application/json

{
  "doctorId": 19,
  "availableDate": "2026-08-20",
  "availableTime": "10:00:00"
}

### GET ALL AVAILABILITY OF DOCTOR

GET http://localhost:8080/availability/doctor/19

###
POST http://localhost:8080/consultations
Content-Type: application/json

{
    "appointmentId": 6,
    "diagnosis": "Viral fever",
    "encryptedNotes": "Patient has mild fever and body pain",
    "consultationDate": "2026-08-27"
}

###
GET http://localhost:8080/consultations/appointment/6


### Add Prescription
POST http://localhost:8080/prescriptions
Content-Type: application/json

{
    "consultId": 3,
    "medicineName": "Paracetamol",
    "instruction": "Take after food",
    "dosage": "500mg"
}

### Get Prescriptions
GET http://localhost:8080/prescriptions/consultation/4
